# This file was generated by GoReleaser. DO NOT EDIT.
cask "xurl" do
  name "xurl"
  desc "Auth-enabled curl-like CLI for the X API"
  homepage "https://github.com/xdevplatform/xurl"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xurl"

  on_macos do
    on_intel do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Darwin_x86_64.tar.gz"
      sha256 "86ad77a1c93dee45a969d7a561b90ba6a97b0176b82027c0868a6867252e8f11"
    end
    on_arm do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Darwin_arm64.tar.gz"
      sha256 "43ac42511b3a23a0d054427faaf8f8d80644c625b223d831ffa4d827e4a0182c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Linux_x86_64.tar.gz"
      sha256 "9914e1e0fddc7f4581378fb847c96d07c128d5ee2f80a8f4d1f38f76229564f9"
    end
    on_arm do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Linux_arm64.tar.gz"
      sha256 "010b7c31a6ceaa5cd061727d0c263e25e275e12df2dfcb57ec7ecfa6531af6d8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xurl"]
    end
  end

  # No zap stanza required
end
