# This file was generated by GoReleaser. DO NOT EDIT.
cask "xurl" do
  name "xurl"
  desc "Auth-enabled curl-like CLI for the X API"
  homepage "https://github.com/xdevplatform/xurl"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xurl"

  on_macos do
    on_intel do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Darwin_x86_64.tar.gz"
      sha256 "30feb126e8ec4f0ff11e19991457b513be1b3d901017fedc9c2b7a12b3875d11"
    end
    on_arm do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Darwin_arm64.tar.gz"
      sha256 "8bffb072d46527dee852e8b2c828633ed81fca99554f4cbe73916d431adcb9c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Linux_x86_64.tar.gz"
      sha256 "0c023a95b65425c807d80beffca739aab71229e2fd1fc5219abd6ae8b203ec07"
    end
    on_arm do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Linux_arm64.tar.gz"
      sha256 "468bc12e4396809368c4c44fdd8e7aab8aa3395e8eeaa5a60cd88cbeab525837"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xurl"]
    end
  end

  # No zap stanza required
end
