# This file was generated by GoReleaser. DO NOT EDIT.
cask "xurl" do
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Darwin_x86_64.tar.gz"
      sha256 "45e28179ceaaa8eb3e44cc799f10cd393b956e3a4f13fd2166cce47a716fc3aa"
    end
    on_arm do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Darwin_arm64.tar.gz"
      sha256 "8712992f96cc6ad5e052419f3dadd4d6d14f413c1bea6d4417dc4d60e4d3886e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Linux_x86_64.tar.gz"
      sha256 "257d12ea177e3bfb60212045c2dfc61dec7aab67099609abf07a7de5aed41f3b"
    end
    on_arm do
      url "https://github.com/xdevplatform/xurl/releases/download/v#{version}/xurl_Linux_arm64.tar.gz"
      sha256 "f97351b9d002c2c6622684e6ef98d4259a74d84127453f1bfe07ebc607b24c22"
    end
  end

  name "xurl"
  desc "Auth-enabled curl-like CLI for the X API"
  homepage "https://github.com/xdevplatform/xurl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xurl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xurl"]
    end
  end

  # No zap stanza required

end
