# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xurl < Formula
  desc "Auth-enabled curl-like CLI for the X API"
  homepage "https://github.com/xdevplatform/xurl"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xdevplatform/xurl/releases/download/v1.0.0/xurl_Darwin_x86_64.tar.gz"
      sha256 "e3dd49b8af8e68a8e2adabe7e4fa555118694f4d399b56a2cdff73cdb6071758"

      def install
        bin.install "xurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xdevplatform/xurl/releases/download/v1.0.0/xurl_Darwin_arm64.tar.gz"
      sha256 "fbb880282226f51b2e61bd0aaf108251847184cbb5a588f16e06ef9a7f3a0982"

      def install
        bin.install "xurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdevplatform/xurl/releases/download/v1.0.0/xurl_Linux_x86_64.tar.gz"
      sha256 "026fae970298842f07e6e467675b134a3e52aadf22c0ecb84f510b6787925cb0"
      def install
        bin.install "xurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdevplatform/xurl/releases/download/v1.0.0/xurl_Linux_arm64.tar.gz"
      sha256 "eecb0a2e7be59341dc422a0acf0914e9ed1eebc3d6265e2942d72d6bae15542a"
      def install
        bin.install "xurl"
      end
    end
  end

  test do
    system "#{bin}/xurl", "version"
  end
end
